SELECT CITY.NAME FROM CITY
WHERE CITY.COUNTRYCODE IN (SELECT COUNTRY.CODE FROM COUNTRY WHERE COUNTRY.CONTINENT = "Africa");

-- OR

SELECT CITY.NAME FROM CITY, COUNTRY 
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT='Africa';