SELECT CONCAT(NAME, REPLACE('(S)', 'S', LEFT(OCCUPATION, 1))) FROM OCCUPATIONS 
ORDER BY NAME;

SELECT REPLACE("There are a total of NUMBER OCCUPATIONs.", "NUMBER OCCUPATION", CONVERT(varchar,COUNT(OCCUPATION))+ " " +LOWER(OCCUPATION))
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION


-- OR

SELECT CONCAT(NAME,"(",left(occupation,1),")") FROM OCCUPATIONS 
ORDER BY NAME;

SELECT CONCAT("There are a total of ", COUNT(OCCUPATION), " " ,LOWER(OCCUPATION),"s.") 
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION